### ISSUE TITLE
Sort and Filter Submissions Table

### ISSUE THREAD

**Issue by dephraiim** [eight-labs/formbase#13]
Currently, it breaks and hangs your application so I removed it.

`@tanstack/react-table` needs the types of data it is receiving, with the submissions, we're storing the submission responses as JSON strings inside the database and the type returned by drizzle is `unknown` therefore we cannot get the exact type of the data being parsed. One thing we can do is to find a way to store the types of responses in the database, which is not ideal.

Another option is to ask the user to add the schema of their database when creating the form and this defeats the whole purpose of the application.

I'm open to ideas.

If we find a way to infer the types from the user's submission, we can send it to the table and we're good to go. One idea I have is to manually  create a form schema from each responses and store it in the database. I'll look into that but as I said, I'm open to ideas.

**Comment by aikins01** [comment]
I'd say the "as" in typescript, but that'll not look right. Could you also look at io-ts since it can do typing at run time for the json
