### ISSUE TITLE
Server Error Error: Cannot set property crypto of #<Object> which has only a getter

### ISSUE THREAD

**Issue by AnkahHarrison** [eight-labs/formbase#68]
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
src/lib/auth/index.ts (12:17) @ eval

  10 | import { type User as DbUser, sessions, users } from "~/server/db/schema";
  11 |
> 12 | globalThis.crypto = webcrypto as unknown as Crypto;
     |                 ^
  13 |
  14 | const adapter = new DrizzlePostgreSQLAdapter(db, sessions, users);
  15 |

**Comment by AnkahHarrison** [comment]
i got this error after setting up and running the project . kindly help me out

**Comment by aikins01** [comment]
What's your nodejs version?

**Comment by AnkahHarrison** [comment]
v20.11.1

**Comment by aikins01** [comment]
Downgrade to nodejs 18 and it should work fine

**Comment by AnkahHarrison** [comment]
Thank you
