### ISSUE TITLE
Request::Accessing Documentation when logged in

### ISSUE THREAD

**Issue by JABClari** [eight-labs/formbase#86]
A request to ensure the _documentation link_ is easily accessible from the dashboard for improved usability.

**Reason**: When logged in, you can access the landing page unless you visit via incognito or log out.

**Comment by ephraimduncan** [comment]
@JABClari would you like to work on this? the ideal place is to have it next to the Onboarding on the user dropdown

**Comment by askadityapandey** [comment]
Hi @ephraimduncan,

I noticed this issue was assigned a week ago, but I haven't seen any updates. If @JABClari is unable to work on it, I'd be happy to take over and ensure the documentation link is easily accessible from the dashboard.

Could you let me know if that’s possible?

Thanks
